# only create secret during installation, skip during upgrades
{{- if .Release.IsInstall }}
---
apiVersion: v1
kind: Secret
metadata:
  name: pebbles
  annotations:
    helm.sh/resource-policy: keep
stringData:
  database-user: pebbles
  database-password: {{ .Values.databasePassword | default (randAlphaNum 16) | quote }}
  pb-secret-key: {{ .Values.pbSecretKey | default (randAlphaNum 32) | quote }}
  admin-email: {{ .Values.adminPassword | quote }}
  admin-password: {{ .Values.adminPassword | default (randAlphaNum 16) | quote }}
{{- end }}
