"""empty message

Revision ID: 78d073f7f858
Revises: h6rg67898907
Create Date: 2019-04-12 09:37:34.524744

"""

# revision identifiers, used by Alembic.
revision = '78d073f7f858'
down_revision = 'h6rg67898907'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('client_id', sa.String(length=40), nullable=False),
    sa.Column('client_secret', sa.String(length=55), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('_redirect_uris', sa.Text(), nullable=True),
    sa.Column('_default_scopes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_client_user_id_users')),
    sa.PrimaryKeyConstraint('client_id', name=op.f('pk_client'))
    )
    op.create_table('grant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('redirect_uri', sa.String(length=255), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('_scopes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], name=op.f('fk_grant_client_id_client')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_grant_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grant'))
    )
    op.create_index(op.f('ix_grant_code'), 'grant', ['code'], unique=False)
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('token_type', sa.String(length=40), nullable=True),
    sa.Column('access_token', sa.String(length=255), nullable=True),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('_scopes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], name=op.f('fk_token_client_id_client')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_token_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token')),
    sa.UniqueConstraint('access_token', name=op.f('uq_token_access_token')),
    sa.UniqueConstraint('refresh_token', name=op.f('uq_token_refresh_token'))
    )
    op.create_unique_constraint(op.f('uq_users_eppn'), 'users', ['eppn'])
    op.drop_constraint(u'uq_users_email', 'users', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'uq_users_email', 'users', ['eppn'])
    op.drop_constraint(op.f('uq_users_eppn'), 'users', type_='unique')
    op.drop_table('token')
    op.drop_index(op.f('ix_grant_code'), table_name='grant')
    op.drop_table('grant')
    op.drop_table('client')
    ### end Alembic commands ###
