"""empty message

Revision ID: 8118b4a1f4d2
Revises: 2b54be9401bd
Create Date: 2018-11-28 12:50:01.310846

"""

# revision identifiers, used by Alembic.
revision = '8118b4a1f4d2'
down_revision = '2b54be9401bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_demo', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_demo')
    ### end Alembic commands ###
