- name: Check if volume block device is mounted -> assume that it is unconfigured ephemeral
  shell: "mount | grep -q '^{{ notebook_host_block_dev_path }} on'"
  register: ephemeral_vanilla
  ignore_errors: yes

- name: Unmount ephemeral on /mnt/
  mount: name=/mnt state=unmounted src={{ notebook_host_block_dev_path }} fstype=ext3
  when: ephemeral_vanilla | success

- name: Wipe the fs from ephemeral
  command: dd if=/dev/zero of={{ notebook_host_block_dev_path }} bs=1M count=10
  when: ephemeral_vanilla | success

- name: Enable lvm2 metadaemon
  service: name=lvm2-lvmetad state=running enabled=yes

- name: Scan for vg_docker volume group
  command: vgdisplay vg_ephemeral
  register: test_vg_ephemeral
  ignore_errors: yes

- name: Create a physical volume on {{ notebook_host_block_dev_path }}
  command: /usr/sbin/pvcreate {{ notebook_host_block_dev_path }}
  when: test_vg_ephemeral.rc==5

- name: Create volume group on ephemeral
  lvg: vg=vg_ephemeral pvs={{ notebook_host_block_dev_path }}
  when: test_vg_ephemeral.rc==5

- name: Check for swap
  shell: 'sudo swapon -s | grep -E "^/"'
  register: swap_configured
  ignore_errors: yes

- name: Create logical volume for swap
  lvol: lv=swap vg=vg_ephemeral size={{ ansible_memtotal_mb * 2 }}M
  when: swap_configured|failed

- name: Run mkswap on swap lv
  command: mkswap /dev/mapper/vg_ephemeral-swap
  when: swap_configured|failed

- name: Run swapon on swap lv
  command: swapon /dev/mapper/vg_ephemeral-swap
  when: swap_configured|failed

- name: Check for docker LV
  command: lvdisplay vg_ephemeral/docker
  register: test_lv_docker
  ignore_errors: yes

- name: Create docker volume
  lvol:
    vg: vg_ephemeral
    lv: docker
    size: 100%FREE
  when: test_lv_docker|failed

- name: Format docker LV with xfs
  filesystem:
    fstype: xfs
    dev: /dev/mapper/vg_ephemeral-docker

- name: Create /var/lib/docker
  file:
    dest: /var/lib/docker
    state: directory
    owner: root
    group: root

- name: Mount /var/lib/docker
  mount:
    src: /dev/mapper/vg_ephemeral-docker
    name: /var/lib/docker
    state: mounted
    fstype: xfs
